name: "Build & Test"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

defaults:
  run:
    shell: bash -l {0}

jobs:  
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        version:
          - mini
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Get Arturo"
        uses: actions/checkout@main
        with:
          repository: arturo-lang/arturo
          submodules: recursive

      - name: Install Nim
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH
          
      - name: Verify dependecies
        run: |
          nim --version
          
      - name: Build Arturo
        run: |
          ./install ${{ matrix.version }} log
          echo "$HOME/.arturo/bin" >> $GITHUB_PATH

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Run unit tests
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tests/runtests.art